kind: PipelineRun
apiVersion: tekton.dev/v1
metadata:
  name: unit-tests
spec:
  taskRunSpecs:
  - pipelineTaskName: run-unit-tests
    stepSpecs:
      - name: run-tests
        computeResources:
          requests:
            cpu: 2
            memory: 1Gi
          limits:
            cpu: 2
            memory: 1Gi
  pipelineSpec:
    params:
      - description: 'Snapshot of the application'
        name: SNAPSHOT
        type: string
    tasks:
      - name: run-unit-tests
        params:
          # This param is automatically set by Konflux when the pipeline is executed
          # https://konflux.pages.redhat.com/docs/users/testing/integration/creating.html#data-injected-into-the-pipelinerun-of-the-integration-test
          - name: SNAPSHOT
            value: "$(params.SNAPSHOT)"
        taskSpec:
          volumes:
          - name: source
            emptyDir: {}
            # Inject the CA since we're cloning from Gitlab.cee
          # - name: trusted-ca
          #   configMap:
          #     name: trusted-ca
          #     items:
          #       - key: ca-bundle.crt
          #         path: ca-bundle.crt
          #     optional: true
          steps:
            - name: clone
              image: registry.access.redhat.com/ubi9-minimal@sha256:6fc28bcb6776e387d7a35a2056d9d2b985dc4e26031e98a2bd35a7137cd6fd71
              env:
                - name: PARAM_SNAPSHOT
                  value: "$(params.SNAPSHOT)"
              script: |
                #!/bin/bash
                set -ex

                # Install the necessary libraries
                microdnf -y install jq git

                # Treat the snapshot data
                echo -e "Running tests for the snapshot:\n ${PARAM_SNAPSHOT}"
                COMPONENT=$(jq -c '.components[0]' <<< "${PARAM_SNAPSHOT}")

                CONTAINER_IMAGE=$(echo "${COMPONENT}" | jq -r '.containerImage')
                GIT_URL=$(echo "${COMPONENT}" | jq -r '.source.git.url')
                GIT_SHA=$(echo "${COMPONENT}" | jq -r '.source.git.revision')

                git clone "$GIT_URL" /source
                git config --global --add safe.directory /source
              volumeMounts:
              - name: source
                mountPath: /source
              # - name: trusted-ca
              #   mountPath: /mnt/trusted-ca
              #   readOnly: true
            - name: run-tests
              # Do not update this image reference, buildah > 1.40 has a change that impacts buildah in podman
              # https://github.com/containers/buildah/issues/6158
              image: registry.access.redhat.com/ubi10/go-toolset:1.25@sha256:182645783ad0a0af4a78d928f2d9167815d59c12cc156aa3c229cf3a49d636d9
              script: |
                #!/bin/bash
                set -ex
                ls -l
                echo
                ls /source
                cd /source
                go test ./pkg/...
              volumeMounts:
              - name: source
                mountPath: /source

